name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install catch2
      run: sudo apt install catch2 -y
    - name: make
      run: make
    - name: make test
      run: make test